// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsM8wxn-Mao2SS9uXwYtCNkTFB2SIB8aw',
    appId: '1:912530479587:web:55a971d761f681079728d6',
    messagingSenderId: '912530479587',
    projectId: 'fir-sample-project-22af5',
    authDomain: 'fir-sample-project-22af5.firebaseapp.com',
    storageBucket: 'fir-sample-project-22af5.firebasestorage.app',
    measurementId: 'G-RLEBQEPJJB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMZ1C-E8-h1HvQNkRLV7t2H3mmt4LLivw',
    appId: '1:912530479587:android:79048b1869d771869728d6',
    messagingSenderId: '912530479587',
    projectId: 'fir-sample-project-22af5',
    storageBucket: 'fir-sample-project-22af5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1Vra4x7sIzCPm__kK7lY7-RA5BgLPK6E',
    appId: '1:912530479587:ios:9d1f48518c0c4c429728d6',
    messagingSenderId: '912530479587',
    projectId: 'fir-sample-project-22af5',
    storageBucket: 'fir-sample-project-22af5.firebasestorage.app',
    iosBundleId: 'com.example.fireBaseSample',
  );
}
